-- ---------------------------------------------------------
-- Project: Paper Plate Manufacturing Operations Analytics
-- Author: Manjeet
-- Tech Stack: MySQL, Python, Power BI
-- ---------------------------------------------------------

-- 1. Create the Database
CREATE DATABASE IF NOT EXISTS PaperPlate_Project;
USE PaperPlate_Project;

-- 2. Create the SalesData Table 
-- (Note: Run this if you are not using the Import Wizard)
CREATE TABLE IF NOT EXISTS SalesData (
    SaleDate DATE,
    Product_Size VARCHAR(50),
    Quantity INT,
    Raw_Material_Used_kg DECIMAL(10, 2),
    Price_Per_Unit DECIMAL(10, 2),
    Total_Revenue DECIMAL(10, 2)
);

-- 3. Basic Data Verification
-- Check the first 10 rows of the imported data
SELECT * FROM SalesData LIMIT 10;

-- 4. Key Performance Indicators (KPIs)
-- Calculate Total Revenue generated by the business
SELECT SUM(Total_Revenue) AS Grand_Total_Sales 
FROM SalesData;

-- Calculate Total Raw Material consumed
SELECT SUM(Raw_Material_Used_kg) AS Total_Material_Used_kg 
FROM SalesData;

-- 5. Business Insights & Analysis
-- Identifying the most popular product size by quantity sold
SELECT Product_Size, SUM(Quantity) AS Units_Sold 
FROM SalesData 
GROUP BY Product_Size 
ORDER BY Units_Sold DESC;

-- Identifying the highest revenue-generating product size
SELECT Product_Size, SUM(Total_Revenue) AS Revenue_Generated
FROM SalesData
GROUP BY Product_Size
ORDER BY Revenue_Generated DESC;

-- 6. Monthly Trend Analysis
-- Checking monthly sales and material usage trends
SELECT 
    MONTHNAME(SaleDate) AS SaleMonth, 
    SUM(Total_Revenue) AS Monthly_Revenue,
    SUM(Raw_Material_Used_kg) AS Monthly_Material_KG
FROM SalesData
GROUP BY SaleMonth
ORDER BY FIELD(SaleMonth, 'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December');